### ISSUE TITLE
Model status

### ISSUE THREAD

**Issue by HDking** [Vishan07/hello-world#4]
Guys, heb het model geupload in `/scripts/FDA_assignment1-model.R`. Alle drie de type regressie modellen zijn er in verwerkt. Ik weet dat er details van de schattingen van de lijnen zijn te vinden, maar daar ben ik op dit moment nog niet achter gekomen. 

Lijkt me een goed idee als @phuckien en ik er morgen aan zitten om de getallen te vinden die we moeten hebben en dan veel screenshots maken voor de mooiheid ;). 

Wellicht @Vishan07 dat je even in een issue laat weten welke je wilt zien, dan kunnen we die morgen genereren. Alles kan, dus individuele regressielijnen (zowel linear, quad als cubic) en de totale gemiddelden. Dus let me know.

**Comment by Vishan07** [comment]
Zie deze issue dus nu pas... maar ik ben helemaal tevreden zo! Awesome work guys!
